### ISSUE TITLE
Custom base model & merge adapter issue

### ISSUE THREAD

**Issue by Kamleshpaul** [huggingface/autotrain-advanced#418] opened 2023-12-20 10:08 UTC
### Feature Request

I fine-tune mistral successfully now i want to further fine-tune and i m not able to select my own model as `base model` and can you please add `--merge-adapter` drop down so we user have option to choose for 

<img width="889" alt="Screenshot 2023-12-20 at 3 35 52 PM" src="https://github.com/huggingface/autotrain-advanced/assets/25585917/5664947f-73ca-421a-ac8f-5f51c00f8e72">

### Motivation

For continues fine-tune  

### Additional Context
Thank you!

**Comment by abhishekkrthakur** [comment] 2023-12-20 14:35
training parameters shouldn't be empty and has merge_adapters. you can just set it to true.

**Comment by Kamleshpaul** [comment] 2023-12-20 14:39
@abhishekkrthakur  that's not issue that i clear while screenshot issue is i already have trained model i need to finetune that means i want to select my own model as `base model`

**Comment by abhishekkrthakur** [comment] 2023-12-20 14:56
> can you please add --merge-adapter drop down so we user have option to choose for
is this not one of the issues?

**Comment by abhishekkrthakur** [comment] 2023-12-20 15:28
so im saying is that one of your issues is already a non issue. its available in training params and im asking why is your training params empty?

**Comment by Kamleshpaul** [comment] 2023-12-20 15:30
oh got it thanks and other issue ?

**Comment by Kamleshpaul** [comment] 2023-12-20 17:44
i used `"merge_adapter": true,` seems it stuck at  it is not moving since 1 hour

<img width="1120" alt="Screenshot 2023-12-20 at 11 12 23 PM" src="https://github.com/huggingface/autotrain-advanced/assets/25585917/44ebba9b-efd4-4d36-9e92-06aaf74fe91c">
<img width="682" alt="Screenshot 2023-12-20 at 11 12 53 PM" src="https://github.com/huggingface/autotrain-advanced/assets/25585917/a667e39a-fa67-4754-bdb7-91e72a7293a5">

**Comment by abhishekkrthakur** [comment] 2023-12-20 17:47
if you use merge adapter, you need to make sure you have a large enough gpu

**Comment by Kamleshpaul** [comment] 2023-12-20 17:49
i m using google colab pro with 
<img width="588" alt="Screenshot 2023-12-20 at 11 19 36 PM" src="https://github.com/huggingface/autotrain-advanced/assets/25585917/19193ef3-b5c1-490c-8fa2-e2c5f78bbc12">

**Comment by abhishekkrthakur** [comment] 2023-12-20 18:05
Use A100 GPU

**Comment by abhishekkrthakur** [comment] 2023-12-20 18:06
ability to add custom models has been implemented. to use custom models pass comma separated custom models in AUTOTRAIN_CUSTOM_MODELS environment variable.
e.g. `export AUTOTRAIN_CUSTOM_MODELS="abhishek/asjfahsdf, abhishek/4572436"`

<img width="1204" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/03c094b8-b42b-4109-90e2-e7910e5213e6">


closing the issue as issues have been addressed.

**Comment by Kamleshpaul** [comment] 2023-12-20 18:22
> Use A100 GPU

not working like no error no progress nothing

**Comment by abhishekkrthakur** [comment] 2023-12-21 12:42
found the merge adapter issue and fixed it. also, all AutoTrain Finetuned LLMs are now deployable to Hugging Face Inference Endpoints WITHOUT merging adapter weights.

**Closed by abhishekkrthakur** 2023-12-21 12:42 UTC
Labels: bug, feature request

**Comment by Kamleshpaul** [comment] 2023-12-21 12:44
Thanks a lot 
really appreciate your work

**Comment by Kamleshpaul** [comment] 2023-12-21 14:59
>config.json: 100% 638/638 [00:00<00:00, 3.36MB/s]
Downloading shards: 100% 8/8 [00:00<00:00, 16.25it/s]
Loading checkpoint shards:  38% 3/8 [00:27<00:45,  9.16s/it]Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'autotrain.trainers.clm', '--training_config', 'quip_v2/training_params.json']' died with <Signals.SIGKILL: 9>.


now i m getting this before i got success not got this error

**Comment by abhishekkrthakur** [comment] 2023-12-21 15:07
that's out of memory error.

**Comment by abhishekkrthakur** [comment] 2023-12-21 15:08
btw, if you dont have a big gpu, you can also merge after training the model. you can either use the space: https://huggingface.co/spaces/autotrain-projects/llm-merge-adapter or just copy paste its code.

**Comment by Kamleshpaul** [comment] 2023-12-21 15:30
i tried that as well not working 
>⚠️ WARNING | 2023-12-21 15:29:10 | __main__:train:471 - Failed to merge adapter weights: local variable 'active_adapters' referenced before assignment
⚠️ WARNING | 2023-12-21 15:29:10 | __main__:train:472 - Skipping adapter merge. Only adapter weights will be saved.
🚀 INFO   | 2023-12-21 15:29:10 | __main__:train:481 - Pushing model to hub...

**Comment by abhishekkrthakur** [comment] 2023-12-21 15:35
whats your base model? i can try it locally to reproduce

**Comment by Kamleshpaul** [comment] 2023-12-21 15:56
`HuggingFaceH4/zephyr-7b-beta`

**Comment by abhishekkrthakur** [comment] 2023-12-21 17:46
i just trained zephyr beta and was able to merge it just fine. Not sure why you are getting the error. make sure of transformer and peft versions: 
peft==0.7.1
transformers==4.36.1


However, just now i looked at `kam414/quip-v1` and it does seem to have the merged weights 🤔 
<img width="495" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/d2fe21f2-75d3-4b01-b877-9f4456929896">

if you have manually added config.json and pytorch-model-*.bin files, please remove them before merging.

**Comment by Kamleshpaul** [comment] 2023-12-21 17:52
this merge i did via https://huggingface.co/spaces/autotrain-projects/llm-merge-adapter

and may be google colab pro will not work in my case

**Comment by abhishekkrthakur** [comment] 2023-12-21 17:57
https://huggingface.co/spaces/autotrain-projects/llm-merge-adapter did you duplicate this and attach a gpu to it?
<img width="717" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/d6f4c30e-f961-4f9e-88a1-52f281d390e6">

**Comment by Kamleshpaul** [comment] 2023-12-21 17:58
nope i just run this

**Comment by abhishekkrthakur** [comment] 2023-12-21 18:10
please follow the instructions my friend :)
you can also do it in colab pro. try this:

```
pip install peft==0.7.1
pip install transformers==4.36.1
```


```
import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

def merge_adapter(base_model_path, target_model_path, adapter_path):
    logger.info("Loading adapter...")
    model = AutoModelForCausalLM.from_pretrained(
        base_model_path,
        torch_dtype=torch.float16,
        low_cpu_mem_usage=True,
        trust_remote_code=True,
    )

    model = PeftModel.from_pretrained(model, adapter_path)

    tokenizer = AutoTokenizer.from_pretrained(
        base_model_path,
        trust_remote_code=True,
    )
    model = model.merge_and_unload()

    logger.info("Saving target model...")
    model.save_pretrained(target_model_path)
    tokenizer.save_pretrained(target_model_path)
```


Anyways, I cloned your model to my profile, duplicated the llm-merge-adapter space with a GPU and was able to successfully merge the model. Here it is: https://huggingface.co/abhishek/quip-v1/tree/main
It took 2mins.

**Comment by Kamleshpaul** [comment] 2023-12-21 18:58
@abhishekkrthakur  can you transfer this repo to me

thanks in advance 🙂

**Comment by abhishekkrthakur** [comment] 2023-12-21 19:00
please use: https://huggingface.co/spaces/huggingface-projects/repo_duplicator 
no need to duplicate this space ;)

**Comment by Kamleshpaul** [comment] 2023-12-21 19:08
WOOW this is awesome 

thanks a lot

**Comment by Kamleshpaul** [comment] 2023-12-22 06:34
@abhishekkrthakur  one last question and please sorry to bother you. 

when i again finetune `kam414/quip-v1` from `kam414/quip-v2` then it's `kam414/quip-v2` base model still shows `HuggingFaceH4/zephyr-7b-beta`

https://huggingface.co/kam414/quip_v2/blob/main/adapter_config.json

so it means no matter how many time i train the model base model will be always `HuggingFaceH4/zephyr-7b-beta` is this Correct me if i m wrong 

if yes then everytime i finetune i need to merge with `HuggingFaceH4/zephyr-7b-beta` ?

**Comment by abhishekkrthakur** [comment] 2023-12-22 08:57
it will show the same name because in v1's config.json, its named as such.
you'll need to manually change the name but keep the same type for the model. ill try it myself then i can give you more info.
