### ISSUE TITLE
[BUG] Dreambooth training not correct

### ISSUE THREAD

**Issue by gobienan** [huggingface/autotrain-advanced#553] opened 2024-03-12 21:48 UTC
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Hugging Face Space/Endpoints

### Interface Used

UI

### UI Screenshots & Parameters

![CleanShot 2024-03-12 at 22 44 56](https://github.com/huggingface/autotrain-advanced/assets/15891299/1b0dc234-368c-4b0e-b911-88588d19b37b)

### Error Logs

There was no error while doing the training. But since the last few updates, it seems like the prompt is not getting recognised  for generating new images based on the trained mode.
 
I can share a model, I have on HuggingFace if that helps. 
But it should also be replicable, since I tried it out a few times yesterday and today.

I haven't changed the default params, except the prompt and base model.

**Comment by abhishekkrthakur** [comment] 2024-03-12 22:13
if you cant share here, please share on autotrain@hf.co; both the models and dataset used so i can take a deeper look.

**Comment by gobienan** [comment] 2024-03-13 08:08
Send you everything over email. I also added the settings I used on Fooocus to generate the images with the trained model. 
In case other people might have a similar issue~

![CleanShot 2024-03-13 at 09 07 19](https://github.com/huggingface/autotrain-advanced/assets/15891299/ec8825f6-e7f6-4425-8e0d-5f6ab1d24b2c)

**Comment by urostrickovic** [comment] 2024-03-17 20:35
Any progress on this issue. I just trained new lora and it is not working still.

**Comment by abhishekkrthakur** [comment] 2024-03-17 20:38
im sorry. i still dont understand the issue. i train models and im able to generate images. please note you need to set parameters right for different types of datasets. can you elaborate what doesnt work?

**Comment by gobienan** [comment] 2024-03-17 20:54
I have shared the images and model with you per email. Could you generate the right images? And what are the right parameters except setting the prompt?

**Comment by urostrickovic** [comment] 2024-03-17 22:12
The issue is even thou i train a lora based on my face and prompt trigger, when I use the lora and activate it with prompt nothing happens. Lora has no impact on the outcome. I created lora with this 1 month ago and works perfectly, but newly trained lora dont work. Using SDXL Lora settings

**Comment by abhishekkrthakur** [comment] 2024-03-18 06:04
ohkay. so the new release does not work for you but the old release does?

**Comment by gobienan** [comment] 2024-03-18 07:51
Exactly that

**Comment by abhishekkrthakur** [comment] 2024-03-18 07:52
im running a few trainings and will come back to this PR later today

**Comment by abhishekkrthakur** [comment] 2024-03-18 08:48
i trained a model without changing any parameters but the prompt on pictures of a dog. here are the pictures:

![2](https://github.com/huggingface/autotrain-advanced/assets/1183441/59a3e022-329d-4bdc-9bbf-a826845810a9)
![5](https://github.com/huggingface/autotrain-advanced/assets/1183441/88f04b5b-627f-4e3d-b16f-6c32dd760873)
![4](https://github.com/huggingface/autotrain-advanced/assets/1183441/4b09d803-1d1a-457a-89e8-c8c90fe84971)
![3](https://github.com/huggingface/autotrain-advanced/assets/1183441/9034e97f-6a15-40f0-a48d-d973daac18a5)
![1](https://github.com/huggingface/autotrain-advanced/assets/1183441/7fb0090d-c537-4e11-bd01-377589c1ebca)


and here is the generated result:
<img width="493" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/e60f99ce-5c42-488c-bc3d-17e621d1ca1d">

**Comment by abhishekkrthakur** [comment] 2024-03-18 08:50
seems to be working fine to me. no? :)

**Comment by gobienan** [comment] 2024-03-18 09:01
So the base model was SD 1.5?
That is the only other parameter I have changed to SDXL.

**Comment by abhishekkrthakur** [comment] 2024-03-18 09:02
base model for the above was sdxl. i can also give sd1.5 a try

**Comment by gobienan** [comment] 2024-03-18 09:04
I am also going to run another job. Here are my settings.
Nothing changed except prompt and base model. 
Four selfie pictures of myself as training data.

![CleanShot 2024-03-18 at 10 03 28](https://github.com/huggingface/autotrain-advanced/assets/15891299/fc1b1799-bba1-4b64-8359-5412e2e10ea1)

**Comment by abhishekkrthakur** [comment] 2024-03-18 09:06
can you try using a simpler prompt without special characters: "photo of a ctgobielhs" ?

**Comment by abhishekkrthakur** [comment] 2024-03-18 09:09
im training a sd1.5 with same data and prompt as the dog above and will update here when done.

**Comment by abhishekkrthakur** [comment] 2024-03-18 09:27
with sd1.5:

<img width="511" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/f2fb0a66-9892-4f8f-a92e-d73a7a35d6ab">

looks fine?

**Comment by abhishekkrthakur** [comment] 2024-03-18 09:36
the above was trained with a resolution of 1024, however, sd1.5 expects 512. training one with 512 now and will update here as soon as it done.

**Comment by abhishekkrthakur** [comment] 2024-03-18 09:44
much better result when correct resolution of 512 is used with sd1.5.

@gobienan are you using 512 for sd1.5? 

<img width="516" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/f96c4b34-db10-49b1-96c8-d94a22ed3636">

**Comment by gobienan** [comment] 2024-03-18 10:22
I dont know how you get images out of it.
I just did the training again with SDXL, since Fooocus does not support SD 1.5.

Base Mode: SDXL from stabilityai.
Prompt: "photo of a ctgobielhs"
Images: 4 Selfie images.
 
But the training did nothing for me. 
When I enter "photo of a ctgobielhs" it generated a camera.

I used a HG space for it with an A10G. 
What am I doing wrong?

As @urostrickovic mentioned, it worked before but does not anymore since the updates from a week ago.

**Comment by urostrickovic** [comment] 2024-03-18 11:02
Im training new set of images now. Screenshoted everything prepared everything. Will post it. Just one question: @gobienan in Huggin Face token should it be "read" or "write". I followed youtube guide and it said to be "write".

**Comment by gobienan** [comment] 2024-03-18 11:04
I used write as well for Google Collab. But I don't think you need one for HF space.

**Comment by urostrickovic** [comment] 2024-03-18 14:14
I just did training here are the screenshots:
Here is Huggingface key: 
![Screenshot 2024-03-18 111022](https://github.com/huggingface/autotrain-advanced/assets/48966542/187fb9bb-bd2a-4acd-a08f-d970fdcd89ef)

Here is settings in NGrok:
![Screenshot 2024-03-18 110834](https://github.com/huggingface/autotrain-advanced/assets/48966542/576ff7c8-2974-4f6e-91e8-902c5eb2fb10)

Here is model used to train:
![model](https://github.com/huggingface/autotrain-advanced/assets/48966542/fb9d5bd3-c927-4ff4-9020-d2f7351f2129)

And here are the results:
![results](https://github.com/huggingface/autotrain-advanced/assets/48966542/baaff71a-bfeb-416e-b837-f9900f72bf0f)

The results dont even look like a model used to train. Here is the whole log : https://pastebin.com/0HnUsYXS

**Comment by urostrickovic** [comment] 2024-03-18 14:20
When you compare that to the Lora i Created on 05. March.2024
Picture of me:
![urost (9)](https://github.com/huggingface/autotrain-advanced/assets/48966542/b3f4b73d-449e-47d7-ad64-c29469a61171)
And the first picture created using the lora
![image](https://github.com/huggingface/autotrain-advanced/assets/48966542/60d150e9-8ab5-4bfc-81fd-8c4742e8620c)
2024-03-05_12-26-15_2387.png so March 5th at around 12:26

**Comment by gobienan** [comment] 2024-03-18 16:33
Hey @sayakpaul,
I tried to follow the guide but it failed for the `use_dora` flag.
Stacktrace:
```
Traceback (most recent call last):
  File "/Users/gobienan/Projects/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1951, in <module>
    main(args)
  File "/Users/gobienan/Projects/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1159, in main
    unet_lora_config = LoraConfig(
TypeError: LoraConfig.__init__() got an unexpected keyword argument 'use_dora'
Traceback (most recent call last):
  File "/Users/gobienan/miniconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Users/gobienan/miniconda3/envs/diffusers/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/Users/gobienan/miniconda3/envs/diffusers/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1057, in launch_command
    simple_launcher(args)
  File "/Users/gobienan/miniconda3/envs/diffusers/lib/python3.10/site-packages/accelerate/commands/launch.py", line 673, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
    ```

**Comment by abhishekkrthakur** [comment] 2024-03-18 16:39
pip install -U peft

**Comment by urostrickovic** [comment] 2024-03-18 16:44
I don't have any more free GPU on google colab. Can anyone make kaggle notebook with these instructions?

**Comment by gobienan** [comment] 2024-03-18 18:48
I used [this notebook](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/SDXL_DreamBooth_LoRA_.ipynb)
you had on the docs. Run everything but the trained model did again nothing. I used custom images,

**Comment by sayakpaul** [comment] 2024-03-19 04:15
Just used that same notebook and the results were okay for me ("dog" dataset):
https://colab.research.google.com/gist/sayakpaul/fb1cf5869851aabd1c1e3661b3720d42/sdxl_dreambooth_lora_.ipynb

@linoytsaban recently used the script to run a couple experiments IIRC on different subjects and it worked okay as well.

**Comment by abhishekkrthakur** [comment] 2024-03-19 06:35
@gobienan @urostrickovic here is a better lora trainer that you can use: https://huggingface.co/spaces/multimodalart/lora-ease

**Comment by sayakpaul** [comment] 2024-03-19 07:17
@gobienan @urostrickovic if it's possible at all and if you could provide the instance images you're using to run training, I can look into training with them and see what we're missing out on.

**Comment by urostrickovic** [comment] 2024-03-19 10:30
Where to send them?

**Comment by sayakpaul** [comment] 2024-03-19 11:07
You can host the images on Hugging Face Hub and I can download from there .Thanks.

**Comment by urostrickovic** [comment] 2024-03-19 11:23
@sayakpaul I dont know how to upload to hugging face so here is a link to my google drive, you can download it there : https://drive.google.com/file/d/1hNWB_AxwmxhxYYHfKoRFMGnbH2a-KeVq/view?usp=sharing
Can you share the lora if it is working with me?

**Comment by sayakpaul** [comment] 2024-03-19 11:30
Hosted the dataset here: https://huggingface.co/datasets/sayakpaul/temp-dataset-autotrain-553.

Could you also share your training and inference settings?

**Comment by urostrickovic** [comment] 2024-03-19 11:55
![Screenshot 2024-03-18 110834](https://github.com/huggingface/autotrain-advanced/assets/48966542/dfbb4b8c-237c-4235-861e-731ffde1bde8)
Here, just used default settings. Just changed the prompt.

From the log at line 132 you can see fully: https://pastebin.com/0HnUsYXS

**Comment by urostrickovic** [comment] 2024-03-19 13:54
@abhishekkrthakur since that lora trainer is paid can i use it in google colab or kagglw since they give 30h free gpu usage.

**Comment by sayakpaul** [comment] 2024-03-19 14:55
Trained two LoRAs -- one with 8bit Adam and another without it (the repos below have the training commands). 

* https://huggingface.co/sayakpaul/temp-autotrain-553-8bit-adam
* https://huggingface.co/sayakpaul/temp-autotrain-553

Dataset used:
https://huggingface.co/datasets/sayakpaul/temp-dataset-autotrain-553

Results below are with the prompt - _photo of ivanman in front of a mountain, best quality_

## 8Bit Adam result

![lora@sayakpaul_temp-autotrain-553-8bit-adam-steps@30-notes@None](https://github.com/huggingface/autotrain-advanced/assets/22957388/9d5bca07-c4ff-4da8-b563-9ff63ec08914)

## Non 8bit Adam result

![lora@sayakpaul_temp-autotrain-553-steps@30-notes@None](https://github.com/huggingface/autotrain-advanced/assets/22957388/e9caff94-aafe-47c7-b1cb-6f2337daac4c)

## Script to perform inference:

```python
from diffusers import DiffusionPipeline, AutoencoderKL
from diffusers.utils import make_image_grid
import argparse
import torch


def main(args):
    vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16).to("cuda")
    pipeline = DiffusionPipeline.from_pretrained(
        "stabilityai/stable-diffusion-xl-base-1.0", vae=vae, torch_dtype=torch.float16
    ).to("cuda")
    print(args.lora_id)
    pipeline.load_lora_weights(args.lora_id, use_safetensors=True)

    images = pipeline(
        prompt=args.prompt,
        num_inference_steps=args.num_inference_steps,
        num_images_per_prompt=args.num_images_per_prompt,
    ).images

    grid_name = f"lora@{args.lora_id.replace('/', '_')}-steps@{args.num_inference_steps}-notes@{args.notes}.png"
    make_image_grid(images, rows=1, cols=args.num_images_per_prompt).save(grid_name)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--lora_id",
        type=str,
        default="sayakpaul/temp-autotrain-553",
        choices=["sayakpaul/temp-autotrain-553", "sayakpaul/temp-autotrain-553-8bit-adam"],
    )
    parser.add_argument("--prompt", type=str, default="photo of ivanman in front of a mountain, best quality")
    parser.add_argument("--num_inference_steps", default=30, type=int)
    parser.add_argument("--num_images_per_prompt", default=4, type=int)
    parser.add_argument("--notes", default=None, type=str)
    args = parser.parse_args()

    main(args)
```

**Comment by urostrickovic** [comment] 2024-03-19 16:52
I think the google colab use Adafactor and the quality is much better. Can you try that

**Comment by gobienan** [comment] 2024-03-20 09:50
@sayakpaul Are you able to generate the images using Fooocus or CompfyUI? 

If I use LoRAs from a few weeks ago (2024-03-06) with Fooocus, they gave great results like these:
![2024-03-03_02-02-41_5529](https://github.com/huggingface/autotrain-advanced/assets/15891299/a831ddc4-e4af-4359-ada9-343cdf3feb8e)

But if I use the LoRAs you made, or any LoRA I trained after the 2024-03-06, the weights/prompt play no role. 

> Trained two LoRAs -- one with 8bit Adam and another without it (the repos below have the training commands).
> 
> * https://huggingface.co/sayakpaul/temp-autotrain-553-8bit-adam
> * https://huggingface.co/sayakpaul/temp-autotrain-553

**Comment by sayakpaul** [comment] 2024-03-20 09:56
Can you try the LoRAs using the [script](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_sdxl.py) I mentioned above using the exact same training parameters? This way, we will be able to point towards what might be causing the issue.

**Comment by gobienan** [comment] 2024-03-20 10:37
It seems like the script does not work on Mac with M1 Chip?
```
RuntimeError: User specified an unsupported autocast device_type 'mps'
``` 

Thats why I used the Google Collab version. But the output was also not working with Fooocus or CompfyUI.
I mean you can generate images with the trained models from Ivan but I can't.
So I would like to try out to generate the images with the code you provided. 

Can I run this on Huggingface? 

> ## Script to perform inference:
> ```python
> from diffusers import DiffusionPipeline, AutoencoderKL
> from diffusers.utils import make_image_grid
> import argparse
> import torch
> 
> 
> def main(args):
>     vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16).to("cuda")
>     pipeline = DiffusionPipeline.from_pretrained(
>         "stabilityai/stable-diffusion-xl-base-1.0", vae=vae, torch_dtype=torch.float16
>     ).to("cuda")
>     print(args.lora_id)
>     pipeline.load_lora_weights(args.lora_id, use_safetensors=True)
> 
>     images = pipeline(
>         prompt=args.prompt,
>         num_inference_steps=args.num_inference_steps,
>         num_images_per_prompt=args.num_images_per_prompt,
>     ).images
> 
>     grid_name = f"lora@{args.lora_id.replace('/', '_')}-steps@{args.num_inference_steps}-notes@{args.notes}.png"
>     make_image_grid(images, rows=1, cols=args.num_images_per_prompt).save(grid_name)
> 
> 
> if __name__ == "__main__":
>     parser = argparse.ArgumentParser()
>     parser.add_argument(
>         "--lora_id",
>         type=str,
>         default="sayakpaul/temp-autotrain-553",
>         choices=["sayakpaul/temp-autotrain-553", "sayakpaul/temp-autotrain-553-8bit-adam"],
>     )
>     parser.add_argument("--prompt", type=str, default="photo of ivanman in front of a mountain, best quality")
>     parser.add_argument("--num_inference_steps", default=30, type=int)
>     parser.add_argument("--num_images_per_prompt", default=4, type=int)
>     parser.add_argument("--notes", default=None, type=str)
>     args = parser.parse_args()
> 
>     main(args)
> ```

**Comment by sayakpaul** [comment] 2024-03-20 11:09
> Can I run this on Huggingface?

I don't have any resources to confirm that. However, you should be able to run the inference code snippet on Colab. 

Alternatively, if you can share your exact training settings and instance images, I can try to run the script on my end and see.

**Comment by gobienan** [comment] 2024-03-20 11:24
It seems like I can create a JupyterLab on Huggingface and do the training there. 
Let's see 🤞
![CleanShot 2024-03-20 at 12 23 16](https://github.com/huggingface/autotrain-advanced/assets/15891299/42222bff-7f18-434a-a6a5-12f42c0ad619)

**Comment by sayakpaul** [comment] 2024-03-20 11:25
Alight. Prefer using the terminal just in case of any state or memory issues :)

**Comment by gobienan** [comment] 2024-03-20 14:02
I got the trained LoRA now with the dog.
![CleanShot 2024-03-20 at 15 01 39](https://github.com/huggingface/autotrain-advanced/assets/15891299/444136d3-1719-4293-a2ed-173ab2dbc2ac)


Is there a way to pass the file instead of the lora id?

```
from huggingface_hub.repocard import RepoCard
from diffusers import DiffusionPipeline
import torch

lora_model_id = <"lora-sdxl-dreambooth-id">
card = RepoCard.load(lora_model_id)
base_model_id = card.data.to_dict()["base_model"]

pipe = DiffusionPipeline.from_pretrained(base_model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")
pipe.load_lora_weights(lora_model_id)
image = pipe("A picture of a sks dog in a bucket", num_inference_steps=25).images[0]
image.save("sks_dog.png")
``

**Comment by sayakpaul** [comment] 2024-03-20 14:34
You can do:

```python
pipelin.load_lora_weights(
    "path-to-the-dir-where-you-have-lora",
     weight_name="pytorch_lora_weights.safetensors"
)
```

**Comment by gobienan** [comment] 2024-03-20 14:41
I have it like this now but seems I still got something wrong :/
```
from huggingface_hub.repocard import RepoCard
from diffusers import DiffusionPipeline
import torch
​
​
pipelin.load_lora_weights(
    "diffusers/examples/dreambooth/lora-trained-xl/pytorch_lora_weights.safetensors",
     weight_name="pytorch_lora_weights.safetensors"
)
pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16)
pipe = pipe.to("cuda")
pipe.load_lora_weights(lora_model_id)
image = pipe("A picture of a sks dog in a bucket", num_inference_steps=25).images[0]
image.save("sks_dog.png")
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[16], line 2
      1 from huggingface_hub.repocard import RepoCard
----> 2 from diffusers import DiffusionPipeline
      3 import torch
      6 pipelin.load_lora_weights(
      7     "diffusers/examples/dreambooth/lora-trained-xl/pytorch_lora_weights.safetensors",
      8      weight_name="pytorch_lora_weights.safetensors"
      9 )

ImportError: cannot import name 'DiffusionPipeline' from 'diffusers' (unknown location)
```

**Comment by gobienan** [comment] 2024-03-20 15:03
Ok finally haha, this is the image I got:
![image](https://github.com/huggingface/autotrain-advanced/assets/15891299/f444a7d1-3057-4c82-a10e-c1ade99fa4df)

**Comment by gobienan** [comment] 2024-03-20 15:16
Here is the space/file I went through: https://gobie-jupyterlab.hf.space/lab/tree/lora_training.ipynb

**Comment by sayakpaul** [comment] 2024-03-20 15:32
Yeah the picture seems fine to me. Sure, the quality can be improved with further hparam tuning. What's the issue? I ran my training on an A100 (80GB).

**Comment by gobienan** [comment] 2024-03-20 15:48
Yeah, it seems like it is working with the python script. 
But for some reason the LoRA's are not working anymore on other platforms like ComfyUI or Fooocus. 
They used to work there as well, and still do with older trained LoRA's.

Only the new LoRA's are not working there. 
Do you have an idea why?

**Comment by abhishekkrthakur** [comment] 2024-03-21 11:42
I'm going to close this issue as this is not really an autotrain or diffusers issue. 
Since you didnt explain earlier what the problem was, it has lead to a great waste of time and misunderstanding between different teams.

If it doesnt work in comfy or focus, create an issue with their authors. The inference script was provided in Google Colab. The same inference script works and thats what autotrain and diffusers do. 

Please refrain from creating confusing issues like this one. 

Thank you, @sayakpaul for investing your precious time in this issue.

**Closed by abhishekkrthakur** 2024-03-21 11:42 UTC
Labels: bug

**Comment by apolinario** [comment] 2024-03-21 14:24
> But for some reason the LoRA's are not working anymore on other platforms like ComfyUI or Fooocus.
> They used to work there as well, and still do with older trained LoRA's.
> 
> Only the new LoRA's are not working there.

The keys of the LoRAs have changed with the new scripts/PEFT integration, and ComfyUI or Fooocus don't support the new keys. One has to convert them from the diffusers format to their format to have it working. 

We convert from the diffusers to the AUTO1111 format in the advanced script: https://github.com/huggingface/diffusers/blob/main/examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py - feel free to reuse the code there for this

**Comment by urostrickovic** [comment] 2024-03-22 11:11
@abhishekkrthakur Can you tell us how to use this link. Do i need to change any of the code. Should i run it localy?

**Comment by abhishekkrthakur** [comment] 2024-03-22 11:24
thanks to @sayakpaul and @apolinario , we ended up adding a kohya converter in AutoTrain. Loras should would with other platforms now. this is is now properly closed.

**Comment by abhishekkrthakur** [comment] 2024-03-22 11:47
try: version 0.7.35

**Comment by gobienan** [comment] 2024-03-22 16:10
Just did the training and generated a few images.
It worked just like it used to 😎🙌🎉

Thanks for including the converter!

**Comment by shatrix** [comment] 2024-06-11 07:54
> Just did the training and generated a few images. It worked just like it used to 😎🙌🎉
> 
> Thanks for including the converter!

could you please share which safetensors file you use in Fooocus after the training ends? and how to?
now we get 2 files from the AutoTrain script
"pytorch_lora_weights.safetensors" & "pytorch_lora_weights_kohya.safetensors"
also in Automatic1111, which one should be used?
